# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas and Xueer
subtitle-quote: "Traveling the World, Together."

description: > # this means to ignore newlines until "baseurl:"
  This is a travel blog describing the adventures of Lucas and Xueer

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lucasandxueer.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
collections: 
     musics:
        output: true
        
     albums:
        output: true
        
     videos:
        output: true
        

# gems: [jekyll-paginate]


#paginate: 5
#paginate_path: "/blog/page:num/" 
